### ISSUE TITLE
can't upload to zeropi

### ISSUE THREAD

**Issue by pomgo** [ZeroPiProject/ZeroPi_package#1]
![image](https://cloud.githubusercontent.com/assets/17764259/13670023/52704522-e702-11e5-9672-f2afeb6a40ec.png)

processing.app.debug.RunnerException
    at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:140)
    at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
    at processing.app.Sketch.upload(Sketch.java:1178)
    at processing.app.Sketch.exportApplet(Sketch.java:1152)
    at processing.app.Sketch.exportApplet(Sketch.java:1124)
    at processing.app.Editor$DefaultExportHandler.run(Editor.java:2430)
    at java.lang.Thread.run(Thread.java:745)
Caused by: processing.app.SerialException: 使用序列埠'COM5'時發生錯誤。
    at processing.app.Serial.touchForCDCReset(Serial.java:87)
    at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:129)
    ... 6 more
Caused by: jssc.SerialPortException: Port name - COM5; Method name - openPort(); Exception type - Port busy.
    at jssc.SerialPort.openPort(SerialPort.java:164)
    at processing.app.Serial.touchForCDCReset(Serial.java:81)
    ... 7 more

**Comment by Makeblock-official** [comment]
what operating system you used?  I need know how to reproduce your problem.
